#!/bin/bash
#
# Common Logging Library (deployShell)
# 
# The MIT License (MIT)
#
# Copyright (c) 2014 Sam Caldwell.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
export LoggerLoaded="yes"

export LogSource="logger"
logInit(){
	export LogSource="$1"
}
logWrite(){
	logger "$LogSource: $1"
	echo "$LogSource: $1"
}
logError(){
	logWrite "ERROR: $1"
	logWrite "try 'help' command for usage information."
	exit 1
}
show_title(){
	echo "=================================================="
	echo "deployShell v.$DEPLOY_SHELL_BUILD [$DEPLOYSHELL_VERSION]"
	echo "(c) 2014 Sam Caldwell."
	echo "=================================================="
}
drawLine(){
	LENGTH=$(echo "$1" | tr -dc 0-9)
	CHAR="$2"
	for i in $(seq 1 1 $LENGTH); do
		echo -n "$CHAR"
	done
}
prettySleep(){
	TIME=$(echo "$1" | tr -dc 0-9)
	for i in $(seq 1 1 $TIME); do
		echo -n "."
		sleep 1
	done
	echo " "
}